export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const GET_LISTINGS_BY_FILTERS = "GET_LISTINGS_BY_FILTERS";
export const GET_LISTINGS_BY_FILTERS_SUCCESS = "GET_LISTINGS_BY_FILTERS_SUCCESS";
export const GET_LISTINGS_BY_FILTERS_FAIL = "GET_LISTINGS_BY_FILTERS_FAIL";
